apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app.kubernetes.io/component: indexer-management
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9117
    targetPort: 9117
  selector:
    app: jackett