apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  labels:
    app: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: IMAGE_PLACEHOLDER
          env:
            - name: RUSTFS_REGION
              value: france
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-secrets
                  key: rustfs_access_key
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-secrets
                  key: rustfs_secret_key
            - name: RUSTFS_CONSOLE_ENABLE
              value: "true"
            - name: RUSTFS_SERVER_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: rustfs-secrets
                  key: rustfs_server_domains
            - name: RUSTFS_ADDRESS
              value: ":9000"
          ports:
            - containerPort: 9000
              name: http-rustfs-1
            - containerPort: 9001
              name: http-rustfs-2
          volumeMounts:
            - name: rustfs-data
              mountPath: /data
              subPath: rustfs
      volumes:
        - name: rustfs-data
          persistentVolumeClaim:
            claimName: rustfs-data
