apiVersion: v1
kind: Service
metadata:
  name: harness
  labels:
    app: harness
spec:
  selector:
    app: harness
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: ssh
      port: 3022
      targetPort: 3022
  type: ClusterIP